version: "3.7"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_HELLO: "hello"
        WORLD: "world"
        # NODE_ENV: "development"
    working_dir: /usr/app
    ports:
      - "3000:3000"
    image: t3-app