import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(['example.hello']);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>
          Create <span>T3</span> App
        </h1>
        <h2>{process.env.NEXT_PUBLIC_HELLO ?? '...not found...'} (client)</h2>
        <h2>{data ? data.greeting : 'Loading'} (server)</h2>
      </div>
    </>
  );
};

export default Home;
